import "dotenv/config";
import type { JobProfile } from "./types.js";

const numberFromEnv = (name: string, fallback: number): number => {
  const value = process.env[name];
  if (!value) return fallback;

  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : fallback;
};

const booleanFromEnv = (name: string, fallback: boolean): boolean => {
  const value = process.env[name];
  if (!value) return fallback;

  return ["1", "true", "yes", "si", "sí"].includes(value.toLowerCase());
};

const listFromEnv = (name: string, separator: string): string[] =>
  (process.env[name] ?? "")
    .split(separator)
    .map((value) => value.trim())
    .filter(Boolean);

export const config = {
  lookbackDays: numberFromEnv("LOOKBACK_DAYS", 60),
  maxJobsPerEmail: numberFromEnv("MAX_JOBS_PER_EMAIL", 20),
  aiMaxCandidates: numberFromEnv("AI_MAX_CANDIDATES", 30),
  aiMinCompatibilityScore: numberFromEnv("AI_MIN_COMPATIBILITY_SCORE", 80),
  enableAiMatching: booleanFromEnv("ENABLE_AI_MATCHING", Boolean(process.env.OPENAI_API_KEY)),
  openAiApiKey: process.env.OPENAI_API_KEY,
  openAiModel: process.env.OPENAI_MODEL ?? "gpt-5-mini",
  cvUrl: process.env.CV_URL,
  serpApiKey: process.env.SERPAPI_API_KEY,
  enableSerpApi: booleanFromEnv("ENABLE_SERPAPI", Boolean(process.env.SERPAPI_API_KEY)),
  serpApiLocation: process.env.SERPAPI_LOCATION ?? "Miami, Florida, United States",
  serpApiCountry: process.env.SERPAPI_GL ?? "us",
  serpApiLanguage: process.env.SERPAPI_HL ?? "es",
  serpApiMonthlyLimit: numberFromEnv("SERPAPI_MONTHLY_LIMIT", 220),
  serpApiRunEveryHours: numberFromEnv("SERPAPI_RUN_EVERY_HOURS", 24),
  serpApiMaxQueriesPerRun: numberFromEnv("SERPAPI_MAX_QUERIES_PER_RUN", 1),
  serpApiQueries: listFromEnv("SERPAPI_QUERIES", "|"),
  sendEmptyDigest: booleanFromEnv("SEND_EMPTY_DIGEST", true),
  dryRun: booleanFromEnv("DRY_RUN", false),
  extraRssFeeds: listFromEnv("EXTRA_RSS_FEEDS", ","),
  defaultRssFeeds: [
    "https://weworkremotely.com/remote-jobs.rss",
    "https://himalayas.app/jobs/rss",
    "https://www.realworkfromanywhere.com/rss.xml"
  ],
  smtp: {
    host: process.env.SMTP_HOST,
    port: numberFromEnv("SMTP_PORT", 465),
    secure: booleanFromEnv("SMTP_SECURE", true),
    user: process.env.SMTP_USER,
    password: process.env.SMTP_PASSWORD,
    from: process.env.EMAIL_FROM,
    to: process.env.EMAIL_TO
  },
  requiredTechTerms: [
    "react",
    "react.js",
    "reactjs",
    "react native",
    "next.js",
    "nextjs",
    "frontend",
    "front-end"
  ],
  seniorityTerms: [
    "ssr",
    "semi senior",
    "semisenior",
    "semi-senior",
    "senior",
    "sr",
    "sênior"
  ],
  exclusionTerms: [
    "junior",
    "jr ",
    "trainee",
    "intern",
    "internship",
    "practicas",
    "prácticas",
    "becario"
  ],
  blockedRegionTerms: [
    "brasil",
    "brazil",
    "brazilian",
    "portuguese",
    "portugues",
    "portugués",
    "portuguese speaker",
    "portuguese speaking",
    "remote brazil",
    "remoto brasil",
    "sao paulo",
    "são paulo",
    "rio de janeiro"
  ],
  spanishSignals: [
    "español",
    "espanol",
    "spanish",
    "spain",
    "españa",
    "latam",
    "latin america",
    "latin-america",
    "américa latina",
    "america latina",
    "hispanoamerica",
    "hispanoamérica",
    "argentina",
    "chile",
    "colombia",
    "mexico",
    "méxico",
    "peru",
    "perú",
    "uruguay",
    "paraguay",
    "ecuador",
    "venezuela",
    "bolivia",
    "costa rica",
    "panama",
    "panamá"
  ],
  regionSignals: [
    "latam",
    "latin america",
    "latin-america",
    "américa latina",
    "america latina",
    "hispanoamerica",
    "hispanoamérica",
    "argentina",
    "chile",
    "colombia",
    "mexico",
    "méxico",
    "peru",
    "perú",
    "uruguay",
    "paraguay",
    "ecuador",
    "venezuela",
    "bolivia",
    "costa rica",
    "panama",
    "panamá",
    "europe",
    "europa",
    "emea",
    "european union",
    "union europea",
    "unión europea",
    "spain",
    "españa",
    "portugal",
    "france",
    "francia",
    "germany",
    "alemania",
    "italy",
    "italia",
    "netherlands",
    "paises bajos",
    "países bajos",
    "belgium",
    "bélgica",
    "belgica",
    "ireland",
    "irlanda",
    "poland",
    "polonia",
    "sweden",
    "suecia",
    "norway",
    "noruega",
    "denmark",
    "dinamarca",
    "finland",
    "finlandia",
    "uk",
    "united kingdom",
    "reino unido",
    "remote europe",
    "remote latam",
    "latam remote",
    "europe remote"
  ],
  europeSignals: [
    "europe",
    "europa",
    "emea",
    "european union",
    "union europea",
    "unión europea",
    "spain",
    "españa",
    "portugal",
    "france",
    "francia",
    "germany",
    "alemania",
    "italy",
    "italia",
    "netherlands",
    "paises bajos",
    "países bajos",
    "belgium",
    "bélgica",
    "belgica",
    "ireland",
    "irlanda",
    "poland",
    "polonia",
    "sweden",
    "suecia",
    "norway",
    "noruega",
    "denmark",
    "dinamarca",
    "finland",
    "finlandia",
    "uk",
    "united kingdom",
    "reino unido",
    "remote europe",
    "europe remote"
  ],
  remoteTerms: [
    "remote",
    "remoto",
    "remota",
    "fully remote",
    "full remote",
    "100% remote",
    "100% remoto",
    "work from home",
    "trabajo remoto",
    "teletrabajo",
    "distributed team"
  ],
  contractTerms: [
    "freelance",
    "contractor",
    "contract",
    "contract-to-hire",
    "b2b",
    "consultant",
    "consultor",
    "independent contractor",
    "prestador de servicios",
    "contrato",
    "por proyecto"
  ],
  acceptableEnglishTerms: [
    "english b1",
    "english level b1",
    "b1 english",
    "ingles b1",
    "inglés b1",
    "nivel b1 de ingles",
    "nivel b1 de inglés",
    "english b2",
    "english level b2",
    "b2 english",
    "ingles b2",
    "inglés b2",
    "nivel b2 de ingles",
    "nivel b2 de inglés",
    "intermediate english",
    "upper intermediate english",
    "ingles intermedio",
    "inglés intermedio",
    "ingles intermedio alto",
    "inglés intermedio alto"
  ],
  blockedEnglishTerms: [
    "english c1",
    "english level c1",
    "c1 english",
    "ingles c1",
    "inglés c1",
    "nivel c1 de ingles",
    "nivel c1 de inglés",
    "english c2",
    "english level c2",
    "c2 english",
    "ingles c2",
    "inglés c2",
    "nivel c2 de ingles",
    "nivel c2 de inglés",
    "advanced english",
    "fluent english",
    "native english",
    "professional english",
    "full professional english",
    "ingles avanzado",
    "inglés avanzado",
    "ingles fluido",
    "inglés fluido",
    "ingles nativo",
    "inglés nativo",
    "english proficiency",
    "excellent english"
  ],
  nursing: {
    enabled: booleanFromEnv("ENABLE_NURSING_PROFILE", false),
    emailTo: process.env.NURSING_EMAIL_TO,
    cvText: process.env.NURSING_CV_TEXT,
    profileName: process.env.NURSING_PROFILE_NAME ?? "Perfil Enfermeria Caracas",
    subjectPrefix: process.env.NURSING_SUBJECT_PREFIX ?? "Ofertas Enfermeria Caracas",
    location: process.env.NURSING_LOCATION,
    minCompatibilityScore: numberFromEnv("NURSING_MIN_COMPATIBILITY_SCORE", 0),
    lookbackDays: numberFromEnv("NURSING_LOOKBACK_DAYS", 7),
    maxJobsPerEmail: numberFromEnv("NURSING_MAX_JOBS_PER_EMAIL", 20),
    aiMaxCandidates: numberFromEnv("NURSING_AI_MAX_CANDIDATES", 20),
    serpApiQueries: listFromEnv("NURSING_SERPAPI_QUERIES", "|"),
    serpApiRunEveryHours: numberFromEnv("NURSING_SERPAPI_RUN_EVERY_HOURS", numberFromEnv("SERPAPI_RUN_EVERY_HOURS", 24)),
    serpApiMaxQueriesPerRun: numberFromEnv("NURSING_SERPAPI_MAX_QUERIES_PER_RUN", 1)
  },
  bakery: {
    enabled: booleanFromEnv("ENABLE_BAKERY_PROFILE", false),
    emailTo: process.env.BAKERY_EMAIL_TO,
    cvText: process.env.BAKERY_CV_TEXT,
    profileName: process.env.BAKERY_PROFILE_NAME ?? "Pasteleria Panaderia Caracas",
    subjectPrefix: process.env.BAKERY_SUBJECT_PREFIX ?? "Ofertas Pasteleria Panaderia Caracas",
    location: process.env.BAKERY_LOCATION,
    minCompatibilityScore: numberFromEnv("BAKERY_MIN_COMPATIBILITY_SCORE", 0),
    lookbackDays: 7,
    maxJobsPerEmail: numberFromEnv("BAKERY_MAX_JOBS_PER_EMAIL", 20),
    aiMaxCandidates: numberFromEnv("BAKERY_AI_MAX_CANDIDATES", 20),
    serpApiQueries: listFromEnv("BAKERY_SERPAPI_QUERIES", "|"),
    serpApiRunEveryHours: numberFromEnv("BAKERY_SERPAPI_RUN_EVERY_HOURS", numberFromEnv("SERPAPI_RUN_EVERY_HOURS", 24)),
    serpApiMaxQueriesPerRun: numberFromEnv("BAKERY_SERPAPI_MAX_QUERIES_PER_RUN", 1)
  }
};

export const oswaldoProfile: JobProfile = {
  id: "react-frontend",
  name: "React Frontend Profile",
  subjectPrefix: "Ofertas React/React Native SSR-SR",
  emailTo: config.smtp.to,
  cvUrl: config.cvUrl,
  lookbackDays: config.lookbackDays,
  maxJobsPerEmail: config.maxJobsPerEmail,
  aiMaxCandidates: config.aiMaxCandidates,
  aiMinCompatibilityScore: config.aiMinCompatibilityScore,
  sourceMode: "tech",
  serpApiQueries: config.serpApiQueries,
  serpApiLocation: config.serpApiLocation,
  serpApiRunEveryHours: config.serpApiRunEveryHours,
  serpApiMaxQueriesPerRun: config.serpApiMaxQueriesPerRun,
  requiredTerms: config.requiredTechTerms,
  optionalTerms: [],
  exclusionTerms: config.exclusionTerms,
  blockedTerms: config.blockedRegionTerms,
  positiveSignals: [...config.seniorityTerms, ...config.remoteTerms, ...config.contractTerms, ...config.regionSignals],
  promptPreferences: [
    "Roles objetivo: SSR/SR React Native, React, Frontend, Mobile, Frontend Engineer.",
    "Perfil principal: frontend/mobile con React, React Native, Next.js y TypeScript.",
    "No asumir experiencia backend fuerte. Node.js o Python basico/secundario puede aceptarse si el foco de la vacante sigue siendo frontend/mobile.",
    "Aceptar fullstack solo si el trabajo real es mayormente frontend y usa React, React Native o Next.js.",
    "Descartar fullstack si el foco real es backend, APIs, microservicios, DevOps, Java, .NET, PHP, Ruby, Go, data engineering o arquitectura backend.",
    "La oferta debe ser full remota. Puede ser mundial, LATAM, Hispanoamerica, Espana o Europa, pero descartar si exige vivir en un pais especifico, hibrido u onsite.",
    "Priorizar LATAM, Hispanoamerica y Espana. Europa solo sirve si la oferta esta en espanol o indica equipo/mercado hispanohablante.",
    "Descartar ofertas de Brasil o que pidan portugues.",
    "Para enviar, debe estar en espanol o indicar equipo/mercado hispanohablante.",
    "Verificar si el ingles es requerido. Si requiere C1, C2, advanced, fluent, native o similar, descartar. Si no pide ingles o pide maximo B1/B2/intermedio, puede pasar.",
    "Extraer rango salarial si aparece en titulo, descripcion, tags o metadata. Si no aparece, usar No indicado."
  ],
  sendGuardrails: {
    acceptedRoles: ["frontend", "mobile", "fullstack_frontend"],
    acceptedRemoteScopes: ["worldwide", "region_restricted"],
    acceptedEnglishRequirements: ["none", "not_specified", "b1", "b2"],
    acceptedSpanishFits: ["spanish_offer", "spanish_speaking_team"],
    allowMediumFrontendForFullstack: true,
    rejectHighBackend: true,
    requireSpanishSignal: true
  }
};

const nursingDefaultQueries = [
  "enfermera Caracas Venezuela",
  "licenciada en enfermeria Caracas",
  "enfermera profesional Caracas",
  "enfermera ocupacional Caracas",
  "enfermera cuidados intensivos Caracas",
  "enfermera oncologia Caracas",
  "enfermera clinica Caracas",
  "enfermera hospital Caracas",
  "enfermera a domicilio Caracas",
  "enfermera cuidado de pacientes Caracas",
  "enfermera pacientes postoperatorios Caracas",
  "enfermera cuidados post operatorios Caracas",
  "enfermera pacientes medicos Caracas",
  "enfermera cuidados a domicilio pacientes Caracas",
  "enfermeria domiciliaria Caracas",
  "enfermera adulto mayor Caracas",
  "enfermera cuidado de heridas Caracas",
  "enfermera alimentacion por sonda Caracas",
  "enfermera administracion de tratamiento Caracas",
  "enfermero Caracas Distrito Capital"
];

const bakeryDefaultQueries = [
  "pastelera Caracas Venezuela",
  "panadera Caracas Venezuela",
  "repostera Caracas Venezuela",
  "decoradora de tortas Caracas",
  "decoracion de tortas Caracas",
  "bomboneria Caracas empleo",
  "chocolateria Caracas empleo",
  "merengues pasteleria Caracas",
  "ayudante de pasteleria Caracas",
  "panaderia pasteleria Caracas empleo"
];

export const nursingProfile: JobProfile = {
  id: "nursing-caracas",
  name: config.nursing.profileName,
  subjectPrefix: config.nursing.subjectPrefix,
  emailTo: config.nursing.emailTo,
  cvText: config.nursing.cvText,
  lookbackDays: config.nursing.lookbackDays,
  maxJobsPerEmail: config.nursing.maxJobsPerEmail,
  aiMaxCandidates: config.nursing.aiMaxCandidates,
  aiMinCompatibilityScore: config.nursing.minCompatibilityScore,
  sourceMode: "serpapi_only",
  serpApiQueries: config.nursing.serpApiQueries.length > 0 ? config.nursing.serpApiQueries : nursingDefaultQueries,
  serpApiLocation: config.nursing.location,
  serpApiRunEveryHours: config.nursing.serpApiRunEveryHours,
  serpApiMaxQueriesPerRun: config.nursing.serpApiMaxQueriesPerRun,
  requiredTerms: ["enfermera", "enfermero", "enfermeria", "enfermería", "nursing", "nurse"],
  optionalTerms: [
    "licenciada en enfermeria",
    "licenciada en enfermería",
    "auxiliar de enfermeria",
    "auxiliar de enfermería",
    "oncologia",
    "oncología",
    "cardiologia",
    "cardiología",
    "clinica",
    "clínica",
    "hospital",
    "domicilio",
    "cuidado de pacientes",
    "cuidados de pacientes",
    "pacientes medicos",
    "pacientes médicos",
    "enfermedades",
    "postoperatorio",
    "post operatorio",
    "post-operatorio",
    "recuperacion",
    "recuperación",
    "hospitalizacion",
    "hospitalización",
    "enfermeria domiciliaria",
    "enfermería domiciliaria",
    "adulto mayor",
    "baño en cama",
    "bano en cama",
    "alimentacion por sonda",
    "alimentación por sonda",
    "cuidado de heridas",
    "cura de heridas",
    "administracion de tratamiento",
    "administración de tratamiento",
    "pacientes covid",
    "covid",
    "ocupacional",
    "instrumentista"
  ],
  exclusionTerms: [
    "medico",
    "médico",
    "odontologo",
    "odontólogo",
    "farmaceutico",
    "farmacéutico",
    "ventas",
    "vendedor",
    "vendedora",
    "representante de ventas",
    "asesor comercial",
    "asesora comercial",
    "promotor",
    "promotora",
    "comercial",
    "marketing",
    "call center",
    "atencion al cliente",
    "atención al cliente",
    "recepcionista",
    "administrativo",
    "administrativa",
    "gerente de farmacia"
  ],
  blockedTerms: ["brazil", "brasil", "portuguese", "portugues", "portugués"],
  positiveSignals: [
    "caracas",
    "distrito capital",
    "venezuela",
    "clinica",
    "clínica",
    "hospital",
    "centro medico",
    "centro médico",
    "salud",
    "paciente",
    "pacientes",
    "postoperatorio",
    "post operatorio",
    "post-operatorio",
    "hospitalizacion",
    "hospitalización",
    "domicilio",
    "cuidados",
    "adulto mayor",
    "heridas",
    "sonda",
    "tratamiento",
    "covid"
  ],
  promptPreferences: [
    "Perfil objetivo: profesional de enfermeria ubicada en Caracas, Venezuela.",
    "Experiencia en clinicas, hospitales, centro medico, enfermeria clinica y atencion de pacientes.",
    "Experiencia en enfermeria clinica, cardiologia, cuidados intensivos y oncologia.",
    "Buscar ofertas presenciales o por turnos en Caracas/Distrito Capital para cualquier trabajo relacionado con enfermeria, cuidado de pacientes, salud asistencial, clinicas, hospitales, centro medico o enfermeria a domicilio.",
    "Incluir especialmente ofertas de cuidado de pacientes medicos, pacientes con enfermedades, pacientes postoperatorios/post-operatorios, recuperacion, hospitalizacion, cuidados a domicilio, oncologia y seguimiento de tratamientos.",
    "Priorizar especialmente enfermeria domiciliaria: administracion de tratamiento, bano en cama, alimentacion por sonda, cuidado/curacion de heridas, atencion de adulto mayor, cuidados propios de enfermeria, pacientes COVID o pacientes respiratorios.",
    "Ser laxo: enviar casi toda oferta que el perfil pueda trabajar si esta relacionada con enfermeria o cuidado de pacientes. No exigir match perfecto ni seniority exacto.",
    "El perfil tiene 59 anos. Descartar si la oferta indica edad maxima menor a 59 o un rango de edad que no incluya 59. Si no menciona edad, puede pasar y debe anotarse como duda/riesgo.",
    "Priorizar Caracas, Distrito Capital o zonas razonables de Caracas. Descartar ofertas fuera de Venezuela o que exijan mudarse lejos.",
    "Descartar siempre ventas, comercial, representante, promotor, marketing, call center, administracion, recepcion, farmacia sin enfermeria, medico, odontologo, laboratorio sin funcion de enfermeria o cargos no asistenciales.",
    "Descartar siempre emergencias, areas criticas, ambulancia, paramedico, terapia intensiva, UCI, trauma, triaje, soporte vital, rescate o traslados criticos.",
    "Descartar cualquier oferta que no sea realmente de enfermeria, enfermero/enfermera, auxiliar de enfermeria, cuidado de pacientes o atencion asistencial directa.",
    "Extraer salario/rango salarial si aparece. Si no aparece, usar No indicado.",
    "Recomendar aplicar si la oferta esta minimamente relacionada con enfermeria/cuidado de pacientes y podria ser trabajable para ella. Usar descartar solo si claramente no corresponde."
  ],
  sendGuardrails: {
    acceptedRoles: ["other"],
    acceptedRemoteScopes: ["country_restricted", "region_restricted", "hybrid", "onsite", "unknown"],
    acceptedEnglishRequirements: ["none", "not_specified", "unknown", "b1", "b2"],
    acceptedSpanishFits: ["spanish_offer", "spanish_speaking_team", "not_specified"],
    allowMediumFrontendForFullstack: true,
    rejectHighBackend: false,
    requireSpanishSignal: false
  }
};

export const bakeryProfile: JobProfile = {
  id: "bakery-caracas",
  name: config.bakery.profileName,
  subjectPrefix: config.bakery.subjectPrefix,
  emailTo: config.bakery.emailTo,
  cvText:
    config.bakery.cvText ??
    "Perfil de ayudante de pasteleria y panaderia en Caracas, Venezuela. Pastelera y panadera con formacion tecnica y experiencia liderando produccion independiente. Experiencia en elaboracion artesanal de pasteleria y panaderia, control de calidad, mise en place, organizacion de recetas, higiene, presentacion de productos y adaptacion a cocinas comerciales. Conocimientos: masas quebradas, batidos, merengues, hojaldre, chocolate y decoracion de tortas. Busca ofertas en panaderia, pasteleria, reposteria, bomboneria, chocolateria, decoracion de tortas o produccion dulce. No busca ayudante de cocina, cocina general, cocina salada, chef de cocina, restaurante general ni cargos fuera de panaderia/pasteleria.",
  lookbackDays: config.bakery.lookbackDays,
  maxJobsPerEmail: config.bakery.maxJobsPerEmail,
  aiMaxCandidates: config.bakery.aiMaxCandidates,
  aiMinCompatibilityScore: config.bakery.minCompatibilityScore,
  sourceMode: "serpapi_only",
  serpApiQueries: config.bakery.serpApiQueries.length > 0 ? config.bakery.serpApiQueries : bakeryDefaultQueries,
  serpApiLocation: config.bakery.location,
  serpApiRunEveryHours: config.bakery.serpApiRunEveryHours,
  serpApiMaxQueriesPerRun: config.bakery.serpApiMaxQueriesPerRun,
  requiredTerms: [
    "pastelera",
    "pastelero",
    "pasteleria",
    "pastelería",
    "panadera",
    "panadero",
    "panaderia",
    "panadería",
    "repostera",
    "repostero",
    "reposteria",
    "repostería",
    "bomboneria",
    "bombonería",
    "chocolateria",
    "chocolatería",
    "tortas",
    "torta",
    "merengues"
  ],
  optionalTerms: [
    "decoracion de tortas",
    "decoración de tortas",
    "decoradora de tortas",
    "decorador de tortas",
    "dulceria",
    "dulcería",
    "postres",
    "chocolate",
    "bombones",
    "masa",
    "panes",
    "panificacion",
    "panificación",
    "horneado",
    "obrador",
    "produccion dulce",
    "producción dulce"
  ],
  exclusionTerms: [
    "ayudante de cocina",
    "auxiliar de cocina",
    "cocina",
    "cocinero",
    "cocinera",
    "chef de cocina",
    "chef ejecutivo",
    "parrillero",
    "pizzero",
    "sushi",
    "barista",
    "mesonero",
    "mesonera",
    "atencion al cliente",
    "atención al cliente",
    "ventas",
    "vendedor",
    "vendedora",
    "cajero",
    "cajera"
  ],
  blockedTerms: ["brazil", "brasil", "portuguese", "portugues", "portugués"],
  positiveSignals: [
    "caracas",
    "distrito capital",
    "venezuela",
    "pasteleria",
    "pastelería",
    "panaderia",
    "panadería",
    "reposteria",
    "repostería",
    "bomboneria",
    "bombonería",
    "decoracion",
    "decoración",
    "tortas",
    "merengues",
    "chocolate"
  ],
  promptPreferences: [
    "Perfil objetivo: ayudante de pasteleria y panaderia en Caracas, Venezuela.",
    "Experiencia aproximada: 2 anos liderando produccion independiente y formacion en panaderia/pasteleria. No exigir experiencia senior.",
    "Especialidades: bomboneria, merengues, decoracion de tortas, chocolate, hojaldre, masas quebradas, batidos, panaderia y pasteleria.",
    "Enviar ofertas relacionadas con pasteleria, panaderia, reposteria, bomboneria, chocolateria, decoracion de tortas, produccion dulce, postres o panificacion.",
    "Ser laxo con experiencia: aceptar trainee, aprendiz, ayudante de pasteleria/panaderia, junior, auxiliar de pasteleria o roles con 0 a 3 anos de experiencia.",
    "Descartar ayudante de cocina, cocina general, cocina salada, restaurante general, chef de cocina, parrilla, sushi, barista, mesonero, caja, ventas, atencion al cliente o cargos fuera de panaderia/pasteleria.",
    "Priorizar Caracas, Distrito Capital o zonas razonables de Caracas. Descartar ofertas fuera de Venezuela o que exijan mudarse lejos.",
    "Extraer salario/rango salarial si aparece. Si no aparece, usar No indicado.",
    "Mantener explicacion de por que matchea y dudas/riesgos para que ella pueda decidir."
  ],
  sendGuardrails: {
    acceptedRoles: ["other"],
    acceptedRemoteScopes: ["country_restricted", "region_restricted", "hybrid", "onsite", "unknown"],
    acceptedEnglishRequirements: ["none", "not_specified", "unknown", "b1", "b2"],
    acceptedSpanishFits: ["spanish_offer", "spanish_speaking_team", "not_specified"],
    allowMediumFrontendForFullstack: true,
    rejectHighBackend: false,
    requireSpanishSignal: false
  }
};
