import "dotenv/config";

const numberFromEnv = (name: string, fallback: number): number => {
  const value = process.env[name];
  if (!value) return fallback;

  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : fallback;
};

const booleanFromEnv = (name: string, fallback: boolean): boolean => {
  const value = process.env[name];
  if (!value) return fallback;

  return ["1", "true", "yes", "si", "sí"].includes(value.toLowerCase());
};

export const config = {
  lookbackDays: numberFromEnv("LOOKBACK_DAYS", 7),
  maxJobsPerEmail: numberFromEnv("MAX_JOBS_PER_EMAIL", 20),
  aiMaxCandidates: numberFromEnv("AI_MAX_CANDIDATES", 30),
  aiMinCompatibilityScore: numberFromEnv("AI_MIN_COMPATIBILITY_SCORE", 90),
  enableAiMatching: booleanFromEnv("ENABLE_AI_MATCHING", Boolean(process.env.OPENAI_API_KEY)),
  openAiApiKey: process.env.OPENAI_API_KEY,
  openAiModel: process.env.OPENAI_MODEL ?? "gpt-5-mini",
  cvUrl: process.env.CV_URL ?? "https://oswaldo-virtual-cv.vercel.app/es",
  serpApiKey: process.env.SERPAPI_API_KEY,
  enableSerpApi: booleanFromEnv("ENABLE_SERPAPI", Boolean(process.env.SERPAPI_API_KEY)),
  serpApiLocation: process.env.SERPAPI_LOCATION ?? "Miami, Florida, United States",
  serpApiCountry: process.env.SERPAPI_GL ?? "us",
  serpApiLanguage: process.env.SERPAPI_HL ?? "es",
  serpApiMonthlyLimit: numberFromEnv("SERPAPI_MONTHLY_LIMIT", 220),
  serpApiRunEveryHours: numberFromEnv("SERPAPI_RUN_EVERY_HOURS", 12),
  serpApiMaxQueriesPerRun: numberFromEnv("SERPAPI_MAX_QUERIES_PER_RUN", 3),
  serpApiQueries: (process.env.SERPAPI_QUERIES ?? "")
    .split("|")
    .map((query) => query.trim())
    .filter(Boolean),
  sendEmptyDigest: booleanFromEnv("SEND_EMPTY_DIGEST", false),
  dryRun: booleanFromEnv("DRY_RUN", false),
  extraRssFeeds: (process.env.EXTRA_RSS_FEEDS ?? "")
    .split(",")
    .map((feed) => feed.trim())
    .filter(Boolean),
  defaultRssFeeds: [
    "https://weworkremotely.com/remote-jobs.rss",
    "https://himalayas.app/jobs/rss",
    "https://www.realworkfromanywhere.com/rss.xml"
  ],
  smtp: {
    host: process.env.SMTP_HOST,
    port: numberFromEnv("SMTP_PORT", 465),
    secure: booleanFromEnv("SMTP_SECURE", true),
    user: process.env.SMTP_USER,
    password: process.env.SMTP_PASSWORD,
    from: process.env.EMAIL_FROM,
    to: process.env.EMAIL_TO
  },
  requiredTechTerms: [
    "react",
    "react.js",
    "reactjs",
    "react native",
    "frontend",
    "front-end"
  ],
  seniorityTerms: [
    "ssr",
    "semi senior",
    "semisenior",
    "semi-senior",
    "senior",
    "sr",
    "sênior"
  ],
  exclusionTerms: [
    "junior",
    "jr ",
    "trainee",
    "intern",
    "internship",
    "practicas",
    "prácticas",
    "becario"
  ],
  spanishSignals: [
    "español",
    "espanol",
    "spanish",
    "spain",
    "españa",
    "latam",
    "latin america",
    "latin-america",
    "américa latina",
    "america latina",
    "hispanoamerica",
    "hispanoamérica",
    "argentina",
    "chile",
    "colombia",
    "mexico",
    "méxico",
    "peru",
    "perú",
    "uruguay",
    "paraguay",
    "ecuador",
    "venezuela",
    "bolivia",
    "costa rica",
    "panama",
    "panamá"
  ],
  regionSignals: [
    "latam",
    "latin america",
    "latin-america",
    "américa latina",
    "america latina",
    "hispanoamerica",
    "hispanoamérica",
    "argentina",
    "chile",
    "colombia",
    "mexico",
    "méxico",
    "peru",
    "perú",
    "uruguay",
    "paraguay",
    "ecuador",
    "venezuela",
    "bolivia",
    "costa rica",
    "panama",
    "panamá",
    "europe",
    "europa",
    "emea",
    "european union",
    "union europea",
    "unión europea",
    "spain",
    "españa",
    "portugal",
    "france",
    "francia",
    "germany",
    "alemania",
    "italy",
    "italia",
    "netherlands",
    "paises bajos",
    "países bajos",
    "belgium",
    "bélgica",
    "belgica",
    "ireland",
    "irlanda",
    "poland",
    "polonia",
    "sweden",
    "suecia",
    "norway",
    "noruega",
    "denmark",
    "dinamarca",
    "finland",
    "finlandia",
    "uk",
    "united kingdom",
    "reino unido",
    "remote europe",
    "remote latam",
    "latam remote",
    "europe remote"
  ],
  europeSignals: [
    "europe",
    "europa",
    "emea",
    "european union",
    "union europea",
    "unión europea",
    "spain",
    "españa",
    "portugal",
    "france",
    "francia",
    "germany",
    "alemania",
    "italy",
    "italia",
    "netherlands",
    "paises bajos",
    "países bajos",
    "belgium",
    "bélgica",
    "belgica",
    "ireland",
    "irlanda",
    "poland",
    "polonia",
    "sweden",
    "suecia",
    "norway",
    "noruega",
    "denmark",
    "dinamarca",
    "finland",
    "finlandia",
    "uk",
    "united kingdom",
    "reino unido",
    "remote europe",
    "europe remote"
  ],
  remoteTerms: [
    "remote",
    "remoto",
    "remota",
    "fully remote",
    "full remote",
    "100% remote",
    "100% remoto",
    "work from home",
    "trabajo remoto",
    "teletrabajo",
    "distributed team"
  ],
  contractTerms: [
    "freelance",
    "contractor",
    "contract",
    "contract-to-hire",
    "b2b",
    "consultant",
    "consultor",
    "independent contractor",
    "prestador de servicios",
    "contrato",
    "por proyecto"
  ],
  acceptableEnglishTerms: [
    "english b1",
    "english level b1",
    "b1 english",
    "ingles b1",
    "inglés b1",
    "nivel b1 de ingles",
    "nivel b1 de inglés",
    "english b2",
    "english level b2",
    "b2 english",
    "ingles b2",
    "inglés b2",
    "nivel b2 de ingles",
    "nivel b2 de inglés",
    "intermediate english",
    "upper intermediate english",
    "ingles intermedio",
    "inglés intermedio",
    "ingles intermedio alto",
    "inglés intermedio alto"
  ],
  blockedEnglishTerms: [
    "english c1",
    "english level c1",
    "c1 english",
    "ingles c1",
    "inglés c1",
    "nivel c1 de ingles",
    "nivel c1 de inglés",
    "english c2",
    "english level c2",
    "c2 english",
    "ingles c2",
    "inglés c2",
    "nivel c2 de ingles",
    "nivel c2 de inglés",
    "advanced english",
    "fluent english",
    "native english",
    "professional english",
    "full professional english",
    "ingles avanzado",
    "inglés avanzado",
    "ingles fluido",
    "inglés fluido",
    "ingles nativo",
    "inglés nativo",
    "english proficiency",
    "excellent english"
  ]
};
